name: Pull Request & Push to Master Branch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - uses: pre-commit/action@v3.0.1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        deps: [highest]
        include:
          - python-version: '3.9'
            deps: lowest-direct
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          uv sync --no-install-project
          uv pip install 'setuptools>=72.0.0'
        env:
          UV_RESOLUTION: ${{ matrix.deps }}

      - name: Typecheck with mypy
        run: uv run mypy mpt
        env:
          UV_RESOLUTION: ${{ matrix.deps }}
      - name: Typecheck with basedpyright
        run: uv run basedpyright mpt
        env:
          UV_RESOLUTION: ${{ matrix.deps }}

      - name: Run tests
        run: uv run -m unittest
        env:
          UV_RESOLUTION: ${{ matrix.deps }}
